### ISSUE TITLE
stacked displays

### ISSUE THREAD

**Issue by vuthanho** [JuliaComputing/PlotlyLight.jl#33]
Stacked displays do not seem to be prioritized (https://discourse.julialang.org/t/display-with-different-plots-show-the-same-plot-several-times/103897).
Related to https://github.com/JuliaLang/julia/pull/30922 ?

**Comment by joshday** [comment]
It is unrelated to that issue.  PlotlyLight uses `Cobweb.Page` to display the plot.  This reuses an `index.html` file in Cobweb's scratch space.  In order to display content in different pages/tabs, you need to use `Cobweb.Tab`.

I just pushed a change to master so that this

```julia
PlotlyLight.SETTINGS.display_object = Cobweb.Tab
```

will let users opt out of reusing the same file.  Note that VS Code uses a different display mechanism that bypasses this `Page`/`Tab` stuff.
